# Generated by Django 5.0 on 2023-12-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clock',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='clock',
            name='check_in_hour',
        ),
        migrations.RemoveField(
            model_name='clock',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='clock',
            name='check_out_hour',
        ),
        migrations.AddField(
            model_name='clock',
            name='check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='clock',
            name='check_out',
            field=models.DateTimeField(null=True),
        ),
    ]
