# Generated by Django 5.0 on 2023-12-21 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0003_alter_clock_check_in_alter_clock_check_out'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clock',
            name='user',
        ),
        migrations.AlterField(
            model_name='clock',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_clocks', to=settings.AUTH_USER_MODEL),
        ),
    ]
